# Generated by Django 2.2.7 on 2020-04-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20190902_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicpage',
            name='retailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
