# Generated by Django 2.2.4 on 2019-09-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='primary_button_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='primary_button_text',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='secondary_button_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='secondary_button_text',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
