# Generated by Django 2.2.4 on 2019-09-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190910_0114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'TOPページ'},
        ),
    ]
